import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { readFile } from "node:fs/promises";
import { after, before, describe, test } from "node:test";
import { fileURLToPath } from "node:url";

import { transform } from "esbuild";
import pg from "pg";

import { PostgresEmailQueue } from "../../src/modules/email/repository.mjs";

const { Pool } = pg;
const databaseUrl = process.env.TEST_DATABASE_URL?.trim();
const schemaName = `swiftline_it_${process.pid}_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
const schemaIdentifier = quoteIdentifier(schemaName);

let pool;
let scopedPool;
let loadedEventRepository;

function quoteIdentifier(identifier) {
  return `"${String(identifier).replaceAll('"', '""')}"`;
}

function qualifiedTable(tableName) {
  return `${schemaIdentifier}.${quoteIdentifier(tableName)}`;
}

function rewriteProductionTables(sql) {
  return String(sql)
    .replaceAll('public."EmailDeliveryRequests"', qualifiedTable("EmailDeliveryRequests"))
    .replaceAll('public."Events"', qualifiedTable("Events"))
    .replaceAll('public."AspNetUsers"', qualifiedTable("AspNetUsers"));
}

function createScopedPool(rawPool) {
  return {
    async connect() {
      const client = await rawPool.connect();
      return {
        query(text, values) {
          return client.query(rewriteProductionTables(text), values);
        },
        release(error) {
          return client.release(error);
        },
      };
    },
    query(text, values) {
      return rawPool.query(rewriteProductionTables(text), values);
    },
  };
}

async function createIsolatedSchema() {
  await pool.query(`CREATE SCHEMA ${schemaIdentifier}`);

  await pool.query(`
    CREATE TABLE ${qualifiedTable("EmailDeliveryRequests")} (
      "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "RecipientEmail" text NOT NULL,
      "RecipientUsername" text NULL,
      "EmailType" text NULL,
      "IsSent" boolean NOT NULL DEFAULT false,
      "Message" text NULL,
      "RetryCount" integer NOT NULL DEFAULT 0,
      "Subject" text NULL,
      "Link" text NULL,
      "EstimatedWait" text NULL,
      "DateCreated" timestamptz NOT NULL DEFAULT now(),
      "LeaseOwner" text NULL,
      "LeaseUntil" timestamptz NULL,
      "LastAttemptAt" timestamptz NULL,
      "NextAttemptAt" timestamptz NOT NULL DEFAULT now(),
      "LastError" text NULL,
      "DeadLetteredAt" timestamptz NULL
    )
  `);

  await pool.query(`
    CREATE TABLE ${qualifiedTable("AspNetUsers")} (
      "Id" text PRIMARY KEY,
      "UserName" text NULL,
      "IsInQueue" boolean NOT NULL DEFAULT false,
      "LastEventJoined" bigint NOT NULL DEFAULT 0
    )
  `);

  await pool.query(`
    CREATE TABLE ${qualifiedTable("Events")} (
      "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "Title" text NOT NULL,
      "Description" text NOT NULL DEFAULT '',
      "AverageTime" integer NOT NULL DEFAULT 0,
      "EventStartTime" time without time zone NOT NULL,
      "EventEndTime" time without time zone NOT NULL,
      "Capacity" integer NOT NULL DEFAULT 0,
      "StaffCount" integer NOT NULL DEFAULT 0,
      "UsersInQueue" integer NOT NULL DEFAULT 0,
      "IsActive" boolean NOT NULL DEFAULT true,
      "AllowAnonymousJoining" boolean NOT NULL DEFAULT false,
      "AllowAutomaticSkips" boolean NOT NULL DEFAULT true,
      "EnableGeographicRestriction" boolean NOT NULL DEFAULT false,
      "Address" text NULL,
      "Latitude" numeric NULL,
      "Longitude" numeric NULL,
      "RadiusInMeters" integer NULL,
      "CreatedBy" text NULL,
      "IsDeleted" boolean NOT NULL DEFAULT false,
      "CreatedAt" timestamptz NOT NULL DEFAULT now()
    )
  `);
}

async function insertEmail(overrides = {}) {
  const row = {
    recipientEmail: "integration@example.test",
    recipientUsername: "Integration User",
    emailType: "QueueUpdate",
    isSent: false,
    message: "Integration test message",
    retryCount: 0,
    subject: "Integration test",
    link: "https://example.test/events/1",
    estimatedWait: "5 minutes",
    dateCreated: new Date(),
    leaseOwner: null,
    leaseUntil: null,
    nextAttemptAt: new Date(Date.now() - 5_000),
    lastError: null,
    deadLetteredAt: null,
    ...overrides,
  };

  const result = await pool.query(
    `
      INSERT INTO ${qualifiedTable("EmailDeliveryRequests")} (
        "RecipientEmail", "RecipientUsername", "EmailType", "IsSent", "Message",
        "RetryCount", "Subject", "Link", "EstimatedWait", "DateCreated",
        "LeaseOwner", "LeaseUntil", "NextAttemptAt", "LastError", "DeadLetteredAt"
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
      RETURNING "Id" AS id
    `,
    [
      row.recipientEmail,
      row.recipientUsername,
      row.emailType,
      row.isSent,
      row.message,
      row.retryCount,
      row.subject,
      row.link,
      row.estimatedWait,
      row.dateCreated,
      row.leaseOwner,
      row.leaseUntil,
      row.nextAttemptAt,
      row.lastError,
      row.deadLetteredAt,
    ],
  );

  return result.rows[0].id;
}

async function readEmail(id) {
  const result = await pool.query(
    `
      SELECT
        "Id" AS id,
        "IsSent" AS "isSent",
        "RetryCount" AS "retryCount",
        "LeaseOwner" AS "leaseOwner",
        "LeaseUntil" AS "leaseUntil",
        "LastError" AS "lastError",
        "DeadLetteredAt" AS "deadLetteredAt"
      FROM ${qualifiedTable("EmailDeliveryRequests")}
      WHERE "Id" = $1
    `,
    [id],
  );
  return result.rows[0];
}

async function insertUser(id, userName) {
  await pool.query(
    `INSERT INTO ${qualifiedTable("AspNetUsers")} ("Id", "UserName") VALUES ($1, $2)`,
    [id, userName],
  );
}

async function insertEvent({
  title,
  description = "Integration event",
  createdBy = "integration-owner",
  createdAt,
  isDeleted = false,
}) {
  const result = await pool.query(
    `
      INSERT INTO ${qualifiedTable("Events")} (
        "Title", "Description", "AverageTime", "EventStartTime", "EventEndTime",
        "Capacity", "StaffCount", "UsersInQueue", "IsActive", "AllowAnonymousJoining",
        "AllowAutomaticSkips", "EnableGeographicRestriction", "Address", "RadiusInMeters",
        "CreatedBy", "IsDeleted", "CreatedAt"
      )
      VALUES ($1, $2, 5, '09:00:00', '17:00:00', 50, 2, 0, true, true, true, false,
              'Integration address', 100, $3, $4, $5)
      RETURNING "Id" AS id
    `,
    [title, description, createdBy, isDeleted, createdAt ?? new Date()],
  );
  return result.rows[0].id;
}

async function loadEventRepository() {
  if (loadedEventRepository) return loadedEventRepository;

  const repositoryPath = fileURLToPath(
    new URL("../../src/modules/events/repository.ts", import.meta.url),
  );
  let source = await readFile(repositoryPath, "utf8");
  const dbImport = 'import { getDbPool } from "@/lib/db";';
  const validationImport = 'import { escapeLikePattern } from "./validation";';
  assert.ok(source.includes(dbImport), "event repository db import changed unexpectedly");
  assert.ok(
    source.includes(validationImport),
    "event repository validation import changed unexpectedly",
  );

  source = source.replace(
    dbImport,
    "const getDbPool = () => globalThis.__swiftlineIntegrationDbPool;",
  );
  source = source.replace(
    validationImport,
    String.raw`const escapeLikePattern = (value) => value.replace(/[\\%_]/g, (character) => "\\" + character);`,
  );

  const transformed = await transform(source, {
    loader: "ts",
    format: "esm",
    target: "es2022",
    sourcefile: repositoryPath,
  });
  const moduleUrl = `data:text/javascript;base64,${Buffer.from(transformed.code).toString("base64")}`;
  loadedEventRepository = (await import(moduleUrl)).eventRepository;
  return loadedEventRepository;
}

async function closeIsolatedDatabase() {
  delete globalThis.__swiftlineIntegrationDbPool;
  if (!pool) return;

  try {
    await pool.query(`DROP SCHEMA IF EXISTS ${schemaIdentifier} CASCADE`);
  } finally {
    await pool.end();
    pool = undefined;
    scopedPool = undefined;
  }
}

if (!databaseUrl) {
  test("PostgreSQL integration tests", { skip: "TEST_DATABASE_URL is not set" }, () => {});
} else {
  describe("bounded Next/email-worker PostgreSQL integration", () => {
    before(async () => {
      pool = new Pool({
        connectionString: databaseUrl,
        max: 8,
        idleTimeoutMillis: 5_000,
        connectionTimeoutMillis: 5_000,
      });
      await pool.query("SELECT 1");
      await createIsolatedSchema();
      scopedPool = createScopedPool(pool);
      globalThis.__swiftlineIntegrationDbPool = scopedPool;
    });

    after(closeIsolatedDatabase);

    test("two concurrent claimers cannot claim the same email row", async () => {
      const id = await insertEmail();
      const first = new PostgresEmailQueue(scopedPool);
      const second = new PostgresEmailQueue(scopedPool);

      const [firstClaims, secondClaims] = await Promise.all([
        first.claim({ limit: 1, leaseOwner: "integration-worker-a", leaseDurationMs: 60_000, maxAttempts: 3 }),
        second.claim({ limit: 1, leaseOwner: "integration-worker-b", leaseDurationMs: 60_000, maxAttempts: 3 }),
      ]);
      const claims = [...firstClaims, ...secondClaims];

      assert.equal(claims.length, 1);
      assert.equal(String(claims[0].id), String(id));
      assert.ok(
        ["integration-worker-a", "integration-worker-b"].includes(claims[0].leaseOwner),
      );

      const row = await readEmail(id);
      assert.equal(row.retryCount, 1);
      assert.equal(row.leaseOwner, claims[0].leaseOwner);
    });

    test("an expired lease is recoverable by another worker", async () => {
      const id = await insertEmail({
        retryCount: 1,
        leaseOwner: "stopped-worker",
        leaseUntil: new Date(Date.now() - 10_000),
        nextAttemptAt: new Date(Date.now() - 10_000),
      });
      const queue = new PostgresEmailQueue(scopedPool);

      const claims = await queue.claim({
        limit: 1,
        leaseOwner: "recovery-worker",
        leaseDurationMs: 60_000,
        maxAttempts: 3,
      });

      assert.equal(claims.length, 1);
      assert.equal(String(claims[0].id), String(id));
      assert.equal(claims[0].leaseOwner, "recovery-worker");
      assert.equal((await readEmail(id)).retryCount, 2);
    });

    test("wrong-owner acknowledgement and failure cannot mutate a claimed row, while the owner can acknowledge it", async () => {
      const id = await insertEmail();
      const queue = new PostgresEmailQueue(scopedPool);
      const claims = await queue.claim({
        limit: 1,
        leaseOwner: "correct-owner",
        leaseDurationMs: 60_000,
        maxAttempts: 3,
      });
      assert.equal(claims.length, 1);

      assert.equal(await queue.acknowledge({ id, leaseOwner: "wrong-owner" }), false);
      assert.deepEqual(
        await queue.fail({
          id,
          leaseOwner: "wrong-owner",
          errorMessage: "should not be recorded",
          retryDelayMs: 1_000,
          maxAttempts: 3,
        }),
        { updated: false, deadLettered: false },
      );

      const unchanged = await readEmail(id);
      assert.equal(unchanged.isSent, false);
      assert.equal(unchanged.retryCount, 1);
      assert.equal(unchanged.leaseOwner, "correct-owner");
      assert.equal(unchanged.lastError, null);

      assert.equal(await queue.acknowledge({ id, leaseOwner: "correct-owner" }), true);
      const acknowledged = await readEmail(id);
      assert.equal(acknowledged.isSent, true);
      assert.equal(acknowledged.leaseOwner, null);
      assert.equal(acknowledged.leaseUntil, null);
      assert.equal(acknowledged.lastError, null);
    });

    test("event repository excludes soft-deleted rows and returns deterministic public search data", async () => {
      await insertUser("integration-owner", "safe-organizer");
      const older = await insertEvent({
        title: "Integration visible older",
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
      });
      const newer = await insertEvent({
        title: "Integration visible newer",
        createdAt: new Date("2026-01-02T00:00:00.000Z"),
      });
      const deleted = await insertEvent({
        title: "Integration deleted",
        createdAt: new Date("2026-01-03T00:00:00.000Z"),
        isDeleted: true,
      });
      const repository = await loadEventRepository();

      assert.equal(await repository.findPublicEvent(BigInt(deleted), null), null);
      const deletedSearch = await repository.searchPublicEvents(
        { page: 1, size: 20, query: "Integration deleted" },
        null,
      );
      assert.equal(deletedSearch.totalCount, 0);
      assert.deepEqual(deletedSearch.rows, []);

      const search = await repository.searchPublicEvents(
        { page: 1, size: 20, query: "Integration" },
        null,
      );
      assert.equal(Number(search.totalCount), 2);
      assert.deepEqual(
        search.rows.map((row) => String(row.id)),
        [String(newer), String(older)],
      );
      assert.deepEqual(
        search.rows.map((row) => row.title),
        ["Integration visible newer", "Integration visible older"],
      );
      assert.equal(search.rows[0].organizer, "safe-organizer");
      assert.equal(search.rows[0].canManage, false);
      assert.equal("PasswordHash" in search.rows[0], false);
      assert.equal("SecurityStamp" in search.rows[0], false);
      assert.deepEqual(Object.keys(search.rows[0]).sort(), [
        "address",
        "allowAnonymousJoining",
        "canManage",
        "description",
        "enableGeographicRestriction",
        "eventStartTime",
        "eventEndTime",
        "id",
        "isActive",
        "organizer",
        "radiusInMeters",
        "staffCount",
        "title",
        "totalCount",
        "usersInQueue",
        "viewerIsInQueue",
        "viewerLastEventJoined",
        "averageTime",
      ].sort());
    });
  });
}
